server:
  ##서버에 접속하는 포트를 설정 / 8020으로 접속 / 1번부터 1023까지는 Well-Known Port 영역이므로 1024~65536번 중에 정해야함.
  port: 8020
  servlet:
    ##서버에 http://localhost:8020으로 접속했을 경우 연결해주는 곳을 지정 / 수업때 배운 HomeController대신 사용해보려 하였으나.
    ##controller에 사용시 localhost:8020/index/WEB-INF/views/index.jsp 로 들어가게되므로 주석처리..
    ##context-path: /index
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
   view:
    ##접두어 / 접미어 view페이지의 앞에는 공통된 폴더 위치인 /WEB-INF/views/를 붙여주고 뒤에는 .jsp를 넣는것
    ##즉 리턴값이 "A"일경우 /WEB-INF/views/A.jsp의 경로에 있는 파일을 리턴해주는것.
    prefix: /WEB-INF/views/
    suffix: .jsp
  ##jdbc Schema(DB)명과 mySQL id, password 각자 설정해야함.
  ## 127.0.0.1는 서버 URL이나 로컬서버 localhost:8020을 사용하기에 통일
  ##추후 공유하지않는 파일로 변경이 가능하다면 할 것.
  dataSource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/Team200?characterEncoding=utf-8
    username: root

    password: root1234

  ##파일업로드 제한용량 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
        
##mybatis 설정
mybatis:
 ##나중에 MapperXML파일에 resultType클래스의 패키지를 안적고 클래스명만 넣고 사용하도록
 ##ex) "boardVO" 이런식으로 사용하게 해주기 위하여 미리 위치를 지정해주는것.
 ##다양한 폴더를 지정하기 위해서는 ","콤마를 통하여 구분한다.
 type-aliases-package: com.team200.proj.vo
 ##mapper파일의 위치를 지정
 mapper-locations: mapper/*Mapper.xml

